source 'https://rubygems.org'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'mongo_mapper'
gem 'bson_ext', ">=1.5.2"
gem 'twilio-ruby'
gem 'bitly'
gem 'heroku'
gem 'thin'
gem 'rdiscount'
gem 'postmark'
gem 'mail'
gem 'json'
